import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class GetDataService {
  constructor() {}

  productData = [
    {
      productId: 101,
      name: 'Stylish Jacket',
      desc: 'A trendy jacket for all seasons.',
      price: 1200,
      category: 'fashion',
    },
    {
      productId: 102,
      name: 'Leather Sofa',
      desc: 'Comfortable leather sofa for your living room.',
      price: 15000,
      category: 'homeandfurniture',
    },
    {
      productId: 103,
      name: 'Smart LED TV',
      desc: 'Ultra HD Smart LED TV with amazing features.',
      price: 45000,
      category: 'appliances',
    },
    {
      productId: 104,
      name: 'Building Blocks',
      desc: 'Creative building blocks set for kids.',
      price: 700,
      category: 'toys',
    },
    {
      productId: 105,
      name: 'Casual Sneakers',
      desc: 'Comfortable and stylish sneakers for daily use.',
      price: 2200,
      category: 'fashion',
    },
    {
      productId: 106,
      name: 'Dining Table Set',
      desc: 'Elegant dining table set for your family.',
      price: 18000,
      category: 'homeandfurniture',
    },
    {
      productId: 107,
      name: 'Microwave Oven',
      desc: 'Efficient and fast cooking microwave oven.',
      price: 8000,
      category: 'appliances',
    },
    {
      productId: 108,
      name: 'Action Figure',
      desc: 'Popular superhero action figure.',
      price: 1200,
      category: 'toys',
    },
    {
      productId: 109,
      name: 'Designer T-shirt',
      desc: 'Comfortable and trendy t-shirt.',
      price: 900,
      category: 'fashion',
    },
    {
      productId: 110,
      name: 'Wall Clock',
      desc: 'Elegant wall clock for home decor.',
      price: 1200,
      category: 'homeandfurniture',
    },
    {
      productId: 111,
      name: 'Refrigerator',
      desc: 'High-capacity refrigerator for fresh storage.',
      price: 25000,
      category: 'appliances',
    },
    {
      productId: 112,
      name: 'Remote Control Car',
      desc: 'Exciting toy car for kids.',
      price: 1500,
      category: 'toys',
    },
    {
      productId: 113,
      name: 'Jeans',
      desc: 'Durable and comfortable jeans.',
      price: 1800,
      category: 'fashion',
    },
    {
      productId: 114,
      name: 'Coffee Table',
      desc: 'Modern coffee table with sleek design.',
      price: 7000,
      category: 'homeandfurniture',
    },
    {
      productId: 115,
      name: 'Air Conditioner',
      desc: 'Cooling air conditioner for hot summers.',
      price: 35000,
      category: 'appliances',
    },
    {
      productId: 116,
      name: 'Plush Teddy Bear',
      desc: 'Soft and cuddly teddy bear.',
      price: 800,
      category: 'toys',
    },
    {
      productId: 117,
      name: 'Winter Coat',
      desc: 'Warm and stylish winter coat.',
      price: 3200,
      category: 'fashion',
    },
    {
      productId: 118,
      name: 'Bookshelf',
      desc: 'Wooden bookshelf for book storage.',
      price: 6000,
      category: 'homeandfurniture',
    },
    {
      productId: 119,
      name: 'Vacuum Cleaner',
      desc: 'Compact and powerful vacuum cleaner.',
      price: 4500,
      category: 'appliances',
    },
    {
      productId: 120,
      name: 'Puzzle Set',
      desc: 'Challenging puzzle set for kids and adults.',
      price: 900,
      category: 'toys',
    },
    {
      productId: 121,
      name: 'Formal Shirt',
      desc: 'Elegant and comfortable formal shirt.',
      price: 1500,
      category: 'fashion',
    },
    {
      productId: 122,
      name: 'Curtains',
      desc: 'Stylish curtains for home decor.',
      price: 3000,
      category: 'homeandfurniture',
    },
    {
      productId: 123,
      name: 'Washing Machine',
      desc: 'Efficient washing machine for daily use.',
      price: 22000,
      category: 'appliances',
    },
    {
      productId: 124,
      name: 'Lego Set',
      desc: 'Creative Lego set for kids.',
      price: 2500,
      category: 'toys',
    },
    {
      productId: 125,
      name: 'Casual Trousers',
      desc: 'Comfortable and stylish trousers.',
      price: 1700,
      category: 'fashion',
    },
    {
      productId: 126,
      name: 'Floor Lamp',
      desc: 'Modern floor lamp for lighting needs.',
      price: 5000,
      category: 'homeandfurniture',
    },
    {
      productId: 127,
      name: 'Mixer Grinder',
      desc: 'Multipurpose mixer grinder for the kitchen.',
      price: 3200,
      category: 'appliances',
    },
    {
      productId: 128,
      name: 'RC Helicopter',
      desc: 'Remote-controlled helicopter for kids.',
      price: 3500,
      category: 'toys',
    },
    {
      productId: 129,
      name: 'Leather Belt',
      desc: 'Stylish and durable leather belt.',
      price: 800,
      category: 'fashion',
    },
    {
      productId: 130,
      name: 'Bean Bag',
      desc: 'Comfortable and stylish bean bag.',
      price: 4000,
      category: 'homeandfurniture',
    },
  ];

  categoriesData = [
    {
      id: 1,
      name: 'Fashion',
      code: 'fashion',
      icon: 'bi bi-person-fill',
    },
    {
      id: 2,
      name: 'Home & Furniture',
      code: 'homeandfurniture',
      icon: 'bi bi-house-fill',
    },
    {
      id: 3,
      name: 'Appliance',
      code: 'appliances',
      icon: 'bi bi-tv-fill',
    },
    {
      id: 4,
      name: 'Toys',
      code: 'toys',
      icon: 'bi bi-puzzle-fill',
    },
    {
      id: 5,
      name: 'All',
      code: 'all',
      icon: 'bi bi-puzzle-fill',
    },
  ];
}
